const serverErrors = new Map([
  // Official 4xx Codes
  [400, "Bad Request: The server cannot or will not process the request due to an apparent client error."],
  [401, "Unauthorized: Authentication is required and has failed or has not yet been provided."],
  [402, "Payment Required: Reserved for future use."],
  [403, "Forbidden: The server is refusing action, possibly due to insufficient permissions."],
  [404, "Not Found: The requested resource could not be found."],
  [405, "Method Not Allowed: The requested HTTP method is not supported for the resource."],
  [406, "Not Acceptable: The requested resource cannot generate content according to the Accept headers sent."],
  [407, "Proxy Authentication Required: The client must first authenticate itself with the proxy."],
  [408, "Request Timeout: The server timed out waiting for the request."],
  [409, "Conflict: Indicates that the request could not be processed due to a conflict in the current state of the resource."],
  [410, "Gone: The requested resource was previously in use but is no longer available."],
  [411, "Length Required: The request did not specify the length of its content."],
  [412, "Precondition Failed: The server does not meet one of the preconditions specified in the request header fields."],
  [413, "Payload Too Large: The request is larger than the server is willing or able to process."],
  [414, "URI Too Long: The provided URI was too long for the server to process."],
  [415, "Unsupported Media Type: The request entity has a media type which the server does not support."],
  [416, "Range Not Satisfiable: The client requested a portion of the file that cannot be supplied."],
  [417, "Expectation Failed: The server cannot meet the requirements of the Expect request-header field."],
  [418, "I'm a Teapot: User attempted to brew coffee with a teapot. The resulting entity body MAY be short and stout."],
  [421, "Misdirected Request: The request was directed at a server that is not able to produce a response."],
  [422, "Unprocessable Entity: The request was well-formed but unable to be followed due to semantic errors."],
  [423, "Locked: The resource being accessed is locked."],
  [424, "Failed Dependency: The request failed because it depended on another request that failed."],
  [425, "Too Early: The server is unwilling to risk processing a request that might be replayed."],
  [426, "Upgrade Required: The client should switch to a different protocol as indicated in the Upgrade header field."],
  [428, "Precondition Required: The origin server requires the request to be conditional."],
  [429, "Too Many Requests: The user has sent too many requests in a given amount of time."],
  [431, "Request Header Fields Too Large: The server is unwilling to process the request due to oversized header fields."],
  [451, "Unavailable For Legal Reasons: Access to the resource is denied due to legal reasons."],

  // Official 5xx Codes
  [500, "Internal Server Error: A generic error message for unexpected server conditions."],
  [501, "Not Implemented: The server does not recognize or cannot fulfill the request method."],
  [502, "Bad Gateway: The server acting as a gateway or proxy received an invalid response from the upstream server."],
  [503, "Service Unavailable: The server cannot handle the request, often due to temporary overload."],
  [504, "Gateway Timeout: The server acting as a gateway or proxy did not receive a timely response from the upstream server."],
  [505, "HTTP Version Not Supported: The server does not support the HTTP version used in the request."],
  [506, "Variant Also Negotiates: Transparent content negotiation results in a circular reference."],
  [507, "Insufficient Storage: The server is unable to store the representation needed to complete the request."],
  [508, "Loop Detected: The server detected an infinite loop while processing the request."],
  [510, "Not Extended: Further extensions to the request are required for the server to fulfill it."],
  [511, "Network Authentication Required: The client needs to authenticate to gain network access."],

  // Unofficial 4xx Codes
  [218, "This is fine: Used by Apache servers."],
  [419, "Page Expired: Used by the Laravel Framework when a CSRF Token is missing or expired."],
  [420, "Method Failure: A deprecated response used by the Spring Framework when a method has failed."],
  [420, "Enhance Your Calm: Returned by Twitter's API when the client is being rate limited."],
  [430, "Request Header Fields Too Large: Used by Shopify when too many URLs are requested within a certain time frame."],
  [450, "Blocked by Windows Parental Controls: Used when Windows Parental Controls are blocking access to a webpage."],
  [498, "Invalid Token: Returned by ArcGIS for Server when a token is expired or invalid."],
  [499, "Token Required: Returned by ArcGIS for Server when a token is required but not provided."],
  [509, "Bandwidth Limit Exceeded: The server has exceeded the bandwidth specified by the server administrator."],
  [529, "Site is overloaded: Used by Qualys in the SSLLabs server testing API to signal that the site can't process the request."],
  [530, "Site is frozen: Used by the Pantheon Systems web platform to indicate a site that has been frozen due to inactivity."],
  [598, "Network read timeout error: Used by some HTTP proxies to signal a network read timeout behind the proxy to a client in front of the proxy."],
  [599, "Network Connect Timeout Error: Used by some HTTP proxies to signal a network connect timeout behind the proxy to a client in front of the proxy."],

  // Unofficial 5xx Codes
  [520, "Web Server Returned an Unknown Error: The origin server returned an empty, unknown, or unexpected response to Cloudflare."],
  [521, "Web Server Is Down: The origin server refused connections from Cloudflare."],
  [522, "Connection Timed Out: Cloudflare timed out contacting the origin server."],
  [523, "Origin Is Unreachable: Cloudflare could not reach the origin server."],
  [524, "A Timeout Occurred: Cloudflare received a TCP connection to the origin server but did not receive a timely HTTP response."],
  [525, "SSL Handshake Failed: Cloudflare could not negotiate an SSL/TLS handshake with the origin server."],
  [526, "Invalid SSL Certificate: Cloudflare could not validate the SSL certificate on the origin web server."],
  [527, "Railgun Error: Used to indicate an interrupted connection between Cloudflare and the origin server's Railgun server."],
  [530, "Error 530 is returned along with a 1xxx error."],
  [460, "Client closed the connection with the load balancer before the idle timeout period elapsed."],
  [463, "The load balancer received an X-Forwarded-For request header with more than 30 IP addresses."],
  [464, "Incompatible protocol versions between Client and Origin server."],
  [561, "Unauthorized: An error around authentication returned by a server registered with a load balancer."],
]);

export default serverErrors;
